# Generated by Django 5.1.3 on 2024-12-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'min_length': 'El nombre debe tener al menos 3 caracteres.'}, help_text='Ingresa un nombre de al menos 3 caracteres.', max_length=255)),
                ('telefono', models.CharField(error_messages={'min_length': 'El teléfono debe tener al menos 7 caracteres.'}, help_text='Ingresa un teléfono de al menos 7 caracteres.', max_length=20)),
                ('fecha_ingreso', models.DateField(help_text='Seleccione la fecha de ingreso en formato DD/MM/AAAA.')),
            ],
        ),
    ]
