# Generated by Django 5.1.3 on 2024-12-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamoLibrosJuegos', '0002_remove_prestamo_pure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_prestamo',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_devolucion',
            new_name='fecha_termino',
        ),
        migrations.RemoveField(
            model_name='juegodemesa',
            name='jugadores',
        ),
    ]
